name: Research Park Job Scraper

on:
  schedule:
    # Run daily at 9:00 AM UTC (4:00 AM EST, 5:00 AM EDT)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Playwright
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run job scraper
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        ANON_KEY: ${{ secrets.ANON_KEY }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python extractor.py
        
    - name: Job completion status
      run: |
        echo "✅ Research Park job scraper completed at $(date)"
        echo "📧 Check your email for new job notifications!" 